#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TelstraApp.Droid.Resource", IsApplication=true)]

namespace TelstraApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::TelstraApp.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::TelstraApp.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::TelstraApp.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::TelstraApp.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::TelstraApp.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::TelstraApp.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::TelstraApp.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::TelstraApp.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::TelstraApp.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::TelstraApp.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::TelstraApp.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::TelstraApp.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::TelstraApp.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::TelstraApp.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::TelstraApp.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TelstraApp.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::TelstraApp.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::TelstraApp.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::TelstraApp.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TelstraApp.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::TelstraApp.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::TelstraApp.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::TelstraApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int findSel_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int findUnsel_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logout_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int reqList = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int reqListGrey = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int requestSel_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int requestUnSel_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int roundbutton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rounded_corner = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash_findme = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int ReqDate = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ReqName = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int ReqStatus = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Searching = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int TableRow01 = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int response_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int room_text = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int selectAllCB = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int weathermap = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Find = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FirstView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LocationSearchLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PendingRequestItemLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ReceivedItemLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RequestItemLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RequestResponse = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RequestResponseNoMap = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Requests = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Response = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ViewResponse = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
